### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by HeroicVillain** [CloakProject/2.0.2.1-Wallets#2]
Exception: St9bad_alloc
std::bad_alloc
cloakcoin-qt.exe in Runaway exception

Installed cloakcoin wallet on different drive than OS

**Comment by cloak-design** [comment]
The team has been investigating this issue and have found an error with the blockchain zip that speeds up the installation of the wallet. The corrupted zip caused a crash with wallets cross platform.

This has been fixed. Please retry your installation.

**Comment by fkosmala** [comment]
All is ok now with the new blockchain zip :)
