### ISSUE TITLE
Failed to extract blockchain archive (error -1)

### ISSUE THREAD

**Issue by jari1984** [CloakProject/2.0.2.1-Wallets#5]
I tried to start CloakCoin DEFENDER on Windows Server 2016, but it fails to extract the blockchain. I see a couple of runtime error windows, and after that a window with the message: 'Failed to extract blockchain archive (error -1)'

Windows Event Viewer shows the following info:
```
Faulting application name: cloakcoin-qt.exe, version: 0.7.8.0, time stamp: 0x72676574
Faulting module name: cloakcoin-qt.exe, version: 0.7.8.0, time stamp: 0x72676574
Exception code: 0x40000015
Fault offset: 0x01023d3d
Faulting process id: 0xff0
Faulting application start time: 0x01d371a9807255e1
Faulting application path: C:\Program Files (x86)\CloakCoin\cloakcoin-qt.exe
Faulting module path: C:\Program Files (x86)\CloakCoin\cloakcoin-qt.exe
Report Id: 44166d84-9f12-400b-98bb-bbf2305f09b1
Faulting package full name: 
Faulting package-relative application ID: 
```

Some ideas: What VC++ runtime is required? Do I need to open specific ports in my firewall?

**Comment by cloak-design** [comment]
Please reach out to the team on rocket chat who will help you investigate https://chat.cloakcoin.com/

**Comment by fkosmala** [comment]
The new blockchain zip is ok for all OSes.
